[package]
name = "yew-app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.38"
log = "0.4.14"
serde = "1.0.123"
wasm-bindgen = "0.2.69"
wasm-logger = "0.2.0"
yew = "0.17.4"
serde_json = "1.0"